# Generated by Django 5.1 on 2024-09-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Europe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('discription', models.TextField()),
            ],
        ),
    ]
