# Generated by Django 5.1 on 2024-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asia',
            options={'verbose_name': 'Добавить Азиатскую', 'verbose_name_plural': 'Страны Азии'},
        ),
        migrations.AlterModelOptions(
            name='europe',
            options={'verbose_name': 'Добавить Европейскую', 'verbose_name_plural': 'Страны Европы'},
        ),
        migrations.AddField(
            model_name='asia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asia',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='asia',
            name='discription',
            field=models.TextField(verbose_name='discription'),
        ),
        migrations.AlterField(
            model_name='europe',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='europe',
            name='discription',
            field=models.TextField(verbose_name='discription'),
        ),
    ]
